appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: cda7jafUiYtHRr7WZs2z4AybwSFf0ReKpo3FKnvaKx6UdMMBSiZuTHEni4p7UyUpLbBBp6sClHa6b9qoUeZCt0C9kPkvcVfvv9uypoy1jbmS76eQElsURysUhN8utkRJqKHl2CsGY47o/8NJJXn37AWJZI+v46dTplC7y/TZmIaKGp7My/KeCoRFCXl4XtzLdhCMhCBPgb8fCUnpkfrM+JiPwKMm/fLH9HIy3BdICCHi8IIjJur66DWjOJ09e+g/NEcQb1wyKSBWD4nsUaRC3BiStoc5NbfWtSUibNMkztzwlTQ9L+awDAgaIKiI2YnojtGpOY5GSRen1I2ugD2OL1UldNECkMd/qnTdC+HHAHfUzz1LqRdG1g1BgN+R/JlMjEQHMhGiN17qxtU7hxgPFV/RjIFTXkbu1Kalx0nrMTMNOqfRfTTMzX1boH60q+M4eqC0zSOIh8orw2wc+5I+zmb1RfMGKEHgoB66fBvstBkHEjwCE2ETcli+Bv0b6bi+uwIwYvILGlENpz2ndY9MBpxxpAYmzvL+gaDGHKjH8zarzbdl4jYpKZu43FXp7lMfJvEhauN/CK3iZgkrcpjY5xS+V0D4o/rFOPWWAw0qDI6C22QiNm5j4CGClqI34UIZsiGHoyVkDAQZ12CSbQsW1IFL6HZXAfZ2g2Wc+p7ZBgI=
